version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "TuPasswordSegura123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vmt-network

  backend:
    build: ./Backend/VMT.Ecommerce
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - vmt-network

  frontend:
    build: ./Frontend/VMT.Ecommerce.Client
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - vmt-network

networks:
  vmt-network: